### ISSUE TITLE
Example for fork

### ISSUE THREAD

**Issue by Al0ngsy** [jcoreio/promisify-child-process#145]
Hallo, can somesome provide me with an example for `fork()` since I somehow can not sending data from parent to child process with `send()`.

When I tried (this is basically the `send()` example from [node.js doc](https://nodejs.org/api/child_process.html#child_process_subprocess_send_message_sendhandle_options_callback)): 

parent.js
```js
import { fork } from 'promisify-child-process'

const child = fork('child.js', {
    encoding: 'utf8',
  })

child.send({ hello: 'world' })

// Causes the child to print: CHILD got message: { hello: 'world' }
child.on('message', (m) => {
  console.log('PARENT got message:', m);
});

await child
```

child.js
```js
process.on('message', (m) => {
  console.log('CHILD got message:', m);
});

// Causes the parent to print: PARENT got message: { foo: 'bar', baz: null }
process.send({ foo: 'bar', baz: NaN });

process.exit()
```

I only get in the console:
```
PARENT got message { foo: 'bar', baz: null }
```
but no 'CHILD got message...' log.

**Comment by jedwards1211** [comment]
I think the child process is exiting before it gets the message.  Remove the `process.exit()` and see if you get the 'CHILD got message' log.

**Comment by Al0ngsy** [comment]
@jedwards1211 yeah thank you that seem to be it

If I do:
```js
process.on('message', (m) => {
  console.log('CHILD got message:', m);
  // Causes the parent to print: PARENT got message: { foo: 'bar', baz: null }
  process.send({ foo: 'bar', baz: NaN });
  process.exit()
});
```
then it print both Parent and Child message.
