### ISSUE TITLE
Time consuming process waits indefinitely

### ISSUE THREAD

**Issue by fawazahmed0** [jcoreio/promisify-child-process#166]
Hi,

It seems that time consuming process wait indefinitely in this package.

I ended up using [exec](https://github.com/fawazahmed0/quran-videos/commit/31632538a5b397b81a09f5a69340399a315cdd8b) which seems to work fine for time consuming process.

In case you would like to look more into this, please let me know, I will add more details in here, on how to reproduce this bug.

**Steps to reproduce:**

**Prerequisite:**

1. Install ffmpeg, if you don't already have one
- Windows:
`choco install ffmpeg`
- Ubutnu:
```
sudo apt update
sudo apt install ffmpeg
```

**Steps:**
1. Unzip [this](https://github.com/fawazahmed0/tem/releases/download/v1.7/debug.zip)
2. Run `workingcode.js`
 `node workingcode.js`
It works fine, takes around 15mins to generate

3. Run `buggycode.js`
`node buggycode.js`
It waits indefinitely, you can confirm by observing the cpu usage

Now try reducing the `repeat` variable to `10` in `buggycode.js` and re run the  code, and it will work just fine.

4. To run the process from command prompt:
`ffmpeg -stream_loop 170 -i "video.mp4" -i "audio.mp3" -vf "subtitles=subtitle.srt:force_style='Alignment=2,OutlineColour=&H100000000,BorderStyle=3,Outline=1,Shadow=0,Fontsize=18,MarginL=0,MarginV=60'" -crf 24 -vcodec libx264 -preset ultrafast -map 0:v -map 1:a -c:a copy -shortest "output.mp4"`

Thanks

**Comment by jedwards1211** [comment]
Yes please let me know, did you see it from another package that uses promisify-child-process or from your own code calling it?

**Comment by fawazahmed0** [comment]
> Yes please let me know
ok I will add more details
> did you see it from another package that uses promisify-child-process or from your own code calling it?

My own code ,see [this](https://github.com/fawazahmed0/quran-videos/commit/31632538a5b397b81a09f5a69340399a315cdd8b)

**Comment by jedwards1211** [comment]
Sorry I should have checked your link first.  Several things I wanted to confirm:

* Is `exec` hitting the default 1MB output limit and erroring out?
* Can you print out the file paths so I can verify whether the exec command you're building ends up being parsed the same way as spawn?
* Would you mind seeing if the following resolves?
```js
await new Promise((resolve, reject) => {
  const child = spawn(...)
  child.on('exit', (code, signal) {
    if (code) reject(new Error('exited with code ' + code))
    if (signal) reject(new Error('exited with signal ' + signal))
    resolve()
  })
})
```

**Comment by jedwards1211** [comment]
It's possible that `spawn` is not emitting the `close` event in your case, maybe I should go back to listening for `exit` as well.

**Comment by fawazahmed0** [comment]
@jedwards1211 I have updated the bugs details with steps to reproduce in your environment, that should surely help you debugging this bug

Thanks

**Comment by fawazahmed0** [comment]
Also one more thing I would like to add to show different behavior from official spawn,
In official spawnSync and it skips the video generation process if the ffmpeg asked for any input(like y/n for overwrite etc), but this library's spawn, wait indefinitely in case a input is asked

**Comment by jedwards1211** [comment]
sorry for the delay, I got distracted from this for awhile...

I tried out your example scripts and video on macOS.  After a few minutes `ffmpeg` CPU usage drops to 0 but it never exits and the node `ChildProcess` object never emits any events.  This behavior even occurs with `require('child_process').spawn` so I think there's some issue with the interaction of `ffmpeg` and node's async `spawn` method.

I'm still waiting to see if your `exec` example will finish. Next I'll see if passing `stdio: 'ignore'` to `require('child_process').spawn` will somehow prevent this issue.

**Comment by fawazahmed0** [comment]
Thanks for looking into this, I tried official `require('child_process').spawnSync` and it worked fine, also the `exec` works fine for me. Though I never tried `require('child_process').spawn` because I am not sure about it's syntax etc (I am use to `Async/Await`)

if you are saying the issue is with official `require('child_process').spawn` then I think I should raise the issue at the [official repo](https://github.com/nodejs/node/issues) then.

Thanks

**Comment by jedwards1211** [comment]
Okay I figured out what the issue is:

> By default, pipes for stdin, stdout, and stderr are established between the parent Node.js process and the spawned subprocess. These pipes have limited (and platform-specific) capacity. If the subprocess writes to stdout in excess of that limit without the output being captured, the subprocess blocks waiting for the pipe buffer to accept more data. This is identical to the behavior of pipes in the shell. Use the { stdio: 'ignore' } option if the output will not be consumed.

(source: https://nodejs.org/api/child_process.html#child_process_child_process)

`exec` and `spawnSync` read from the child process pipes, so they don't fill up (though `exec` and `spawnSync` have a `maxBuffer` limit and will error out if they read more than `maxBuffer` bytes from the child process).

But `require('child_process').spawn` (and `require('promisify-child-process').spawn`, which uses async spawn under the hood) don't read from the child process pipes and they fill up after `ffmpeg` writes `frame=34531 fps=147 q=28.0 size=  112896kB time=00:09:35.28 bitrate=1607.6kbits/s speed=2.45x` enough times.

You can prevent this problem with async spawn by using the `stdio: 'ignore'` or `stdio: 'inherit'` options.
