### ISSUE TITLE
help me fix this pls

### ISSUE THREAD

**Issue by huawder** [jcoreio/promisify-child-process#190]
![image](https://user-images.githubusercontent.com/96999556/147889964-04dd320c-8f59-413b-afbd-58980dce5dc2.png)

**Comment by jedwards1211** [comment]
I've seen that, `node-tcp-proxy` logs that to the console: https://github.com/tewarid/node-tcp-proxy/blob/2da07cea6a15097326700de098f26dd47340b323/tcp-proxy.js#L51

**Comment by jedwards1211** [comment]
oh I see you were commenting in a TCP proxy issue
