### ISSUE TITLE
Can this work for browser

### ISSUE THREAD

**Issue by Kali95739** [jcoreio/promisify-child-process#206]
?

**Comment by Kali95739** [comment]
If so where is index.cjs for mjs file?

**Comment by jedwards1211** [comment]
the build script transpiles `src/index.js` to `index.cjs`.  But I'm confused why you would want to use this in the browser?  I haven't heard of trying to spawn child processes from the browser

**Comment by Kali95739** [comment]
Just because I figured with node core modules like fs being able to be used
in the browser I figure there is a way to do the same with child_process
either be a es6 version transpiler or something like electron or etc

**Comment by Kali95739** [comment]
Rollup I believe has a polyfill for child_process also

**Comment by jedwards1211** [comment]
okay well then as long as a given build tool can polyfill `child_process` in `.cjs` files imported from `.mjs` it can work.  If you actually try to use `child_process` polyfills with this package and run into problems in the future, we can reopen this when that happens
